# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: FORSUC INTERNATIONAL TECHNOLOGIES
title_separator: "|"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Get abreast with state-of-the-art information communication technology at the least possible cost
baseurl: "/forsuc-intl" # the subpath of your site, e.g. /blog will be name of repository on github if i want to host it inside ofspain, else, if i want to host it on separate github account, i leave it blank
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
logo: "/assets/images/logo.jpg"
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Build settings
markdown: kramdown
#theme: minima
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
repository: ofspain/forsuc-intl
plugins:
  - jekyll-feed
  - jekyll-include-cache

collections:
  trainning:
    output: true
    permalink: /:collection/:title/
  solar-inverter:
    output: true
    permalink: /:collection/:title/
  repairs:
    output: true
    permalink: /:collection/:title/
  telecom: 
    output: true
    permalink: /:collection/:title/
  cctv:
    output: true
    permalink: /:collection/:title/
  posts:
    output: true
    permanlink: /blog/:title

defaults:
  # _trainning
  - scope:
      path: ""
      type: trainning
    values:
      layout: single
      author_profile: false
      share: true
  # _solar-inverter
  - scope:
      path: ""
      type: solar-inverter
    values:
      layout: single
      author_profile: false
      share: true
  # _repairs
  - scope:
      path: ""
      type: repairs
    values:
      layout: single
      author_profile: false
      share: true
  # _telecom
  - scope:
      path: ""
      type: telecom
    values:
      layout: single
      author_profile: false
      share: true  
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
